#' Save Scree Plots to Files
#'
#' Saves all scree plots generated by \code{\link{create_som_scree_plot}} to PNG
#' files in a specified directory. Creates individual plots and a combined
#' multi-panel plot.
#'
#' @param scree_results A results object from \code{\link{create_som_scree_plot}}
#'   containing a \code{plots} element with ggplot objects.
#' @param output_dir Character. Directory where plots will be saved. Default is
#'   './plots/'. Directory will be created if it doesn't exist.
#'
#' @return None. Function is called for side effects (saving plot files).
#'
#' @details
#' \strong{Files Created:}
#' \enumerate{
#'   \item \code{scree_accuracy.png} - Mean accuracy vs grid size
#'   \item \code{scree_f1.png} - Mean weighted F1 vs grid size
#'   \item \code{accuracy_vs_nodes.png} - Mean accuracy vs total nodes
#'   \item \code{accuracy_by_elevation.png} - All elevation bands comparison
#'   \item \code{marginal_improvement.png} - Rate of improvement plot
#'   \item \code{scree_combined.png} - Combined 2×2 panel of key plots
#' }
#'
#' \strong{File Specifications:}
#' \itemize{
#'   \item Individual plots: 10" × 6" at 300 DPI
#'   \item Combined plot: 16" × 12" at 300 DPI
#'   \item Format: PNG with white background
#' }
#'
#' \strong{Combined Plot Layout:}
#' The combined plot includes:
#' \itemize{
#'   \item Top left: Accuracy scree plot
#'   \item Top right: F1 scree plot
#'   \item Bottom left: Marginal improvement plot
#'   \item Bottom right: (empty in 2×2 grid)
#' }
#'
#' @examples
#' \dontrun{
#' # Create scree plots
#' scree_results <- create_som_scree_plot(grid_sizes = 10:20)
#'
#' # Save all plots to default directory
#' save_scree_plots(scree_results)
#'
#' # Save to custom directory
#' save_scree_plots(scree_results, output_dir = './figures/scree_plots/')
#'
#' # Files will be saved with messages printed to console
#' }
#'
#' @note
#' The function will create the output directory if it doesn't exist. Existing
#' files with the same names will be overwritten without warning.
#'
#' @seealso \code{\link{create_som_scree_plot}}
#'
#' @importFrom ggplot2 ggsave
#' @importFrom gridExtra grid.arrange
#' @export
save_scree_plots <- function(scree_results, output_dir = './plots/') {
  
  # Create directory if it doesn't exist
  dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
  
  ggplot2::ggsave(paste0(output_dir, "scree_accuracy.png"), 
         scree_results$plots$accuracy_scree, 
         width = 10, height = 6, dpi = 300)
  
  ggplot2::ggsave(paste0(output_dir, "scree_f1.png"), 
         scree_results$plots$f1_scree, 
         width = 10, height = 6, dpi = 300)
  
  ggplot2::ggsave(paste0(output_dir, "accuracy_vs_nodes.png"), 
         scree_results$plots$accuracy_vs_nodes, 
         width = 10, height = 6, dpi = 300)
  
  ggplot2::ggsave(paste0(output_dir, "accuracy_by_elevation.png"), 
         scree_results$plots$by_elevation, 
         width = 10, height = 6, dpi = 300)
  
  ggplot2::ggsave(paste0(output_dir, "marginal_improvement.png"), 
         scree_results$plots$marginal_improvement, 
         width = 10, height = 6, dpi = 300)
  
  # Save combined plot
  combined <- gridExtra::grid.arrange(
    scree_results$plots$accuracy_scree,
    scree_results$plots$f1_scree,
    scree_results$plots$marginal_improvement,
    ncol = 2, nrow = 2
  )
  
  ggplot2::ggsave(paste0(output_dir, "scree_combined.png"), 
         combined, 
         width = 16, height = 12, dpi = 300)
  
  cat("\nAll plots saved to:", output_dir, "\n")
}
